---
page_title: Faculty
---

![Tianshu Wang](/img/tianshu-wang.jpg)

## Tianshu Wang

Acclaimed by the press as a “superbly talented pianist” who plays with “prodigious technique and eloquent phrasing”, Steinway Artist Tianshu Wang has graced concert stages in the United States, China，Mexico，Singapore, Thailand, and Taiwan. Invitations to perform in Europe are also in the offing. Winner of many competitions, including a national first prize, she is active in both solo and collaborative performance and has performed with major orchestras in China and the United States. She will make her debut at Carnegie Hall in November of 2016. She has been a regular juror of National Piano Competitions in China since 2005, and has performed live on CCTV. Respected as a distinguished artist and teacher in her native China, she was featured in a cover story of the country’s most prestigious piano magazine, Piano Artistry.
	Dr. Wang is currently Professor and Head of the Keyboard Area at Capital University’s Conservatory of Music in Columbus, Ohio. She received the Praestantia Award for Distinguished Teaching in 2011, the highest honor given to a faculty member at the university.  Prior to Capital, she served on the piano faculty of Sweet Briar College in Virginia. She is also a professor and chair of the Piano Department at the Shenyang Conservatory of Music in China, where she teaches for part of the year.
	Dr. Wang holds degrees from the University of Arizona (M.M. and D.M.A. in Piano Performance) and the Shanghai Conservatory of Music (B.M. in Piano Performance). Her teachers include Zhu Yafen, who also taught Lang Lang, and Nicholas Zumbro, a student of the legendary Rosina Lhévienne.
	Dr. Wang’s studio at Capital University includes a number of outstanding young pianists. Many of them are national and international competition winners. Upon graduation, these students go to the most prestigious graduate music schools to pursue higher degrees including Eastman School of Music, Manhattan School of Music, University of Michigan, Indiana University, University of California Los Angeles, and Westminster Choir College, to name just a few. Most recently, she is featured in a cover story of the Capital Magazine, “Crossing the Musical Boarders”.
 	Tianshu Wang’s biography appears in Who’s Who in America, Who’s Who of American Women, and Who’s Who in China. The CD set “Encyclopedia of Chinese Classical Piano Music” in which she is featured as a major performer, has been a best seller in China; and her chamber music CDs, which were published by Albany and Mark Records, have been well received by both the public and critics. Her solo album entitled “Piano in China” that was released on the Albany label was featured on the cover of Fanfare magazine (March/April issue of 2012) with an extensive interview article and some enthusiastic reviews.
